# A list of third-party dependencies cached on OSSCI S3.
# All updates to this config will be automatically applied by "sync-s3-cache" workflow.
# For more information and documentation, see:
# https://github.com/pytorch/builder/main/thirdparty_deps/README.md
# and https://github.com/pytorch/builder/pull/1096
validation:
  # Key: allowed S3 bucket name
  # Value: list of allowed S3 key prefixes
  ossci-windows:
    - "test/"
    - "miniconda/"
  ossci-linux:
    - "test/"
    - "cuda/"
    - "cudnn/"
  ossci-macos:
    - "test/"

urls:
  - bucket: ossci-windows
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
    key: miniconda/Miniconda3-latest-Windows-x86_64.exe
