# This workflow uploads third-party dependencies to OSSCI S3.
# For more information and documentation, see:
# * https://github.com/pytorch/builder/main/thirdparty_deps/README.md
# * https://github.com/pytorch/builder/pull/1096
# * .github/pytorch-cached-s3-dependencies.yml

name: Update S3 dependencies on public OSSCI S3 buckets
on:
  push:
  workflow_dispatch:

jobs:
  sync-s3-cache:
    runs-on: ubuntu-18.04
#    if: ${{ github.repository == 'pytorch/pytorch' }}
    steps:
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master
        with:
          submodules: false
          fetch-depth: 1
      - name: Sync S3 file cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_UPDATE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_UPDATE_SECRET_ACCESS_KEY }}
        uses: docker://pytorch/sync_s3_thirdparty_deps
        with:
          args: ".github/pytorch-cached-s3-dependencies.yml"
